# -*- coding: utf-8 -*-
"""rectangle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15f9kkX6NhKby4g6fS8qOkj1o_Ht-Sv9m
"""

'''================= Class ===================='''
class Rectangle:
    def __init__(self, height, width):
        self.h = height
        self.w = width

'''================= Objects ===================='''
rect1 = Rectangle(20, 30)
rect2 = Rectangle(50, 40)

rect1.area = rect1.h * rect1.w
rect2.area = rect2.h * rect2.w

print(f"Area of Reactangle-1 = {rect1.area}")
print(f"Area of Reactangle-2 = {rect2.area}")

'''================= Class ===================='''
class Car:
    def __init__(self, speed, color):
        print(f"\nSpeed --> {speed}")
        print(f"Color --> {color}")
        self.s = speed
        self.c = color
        print("__init__() is called")

'''================= Objects ===================='''
ford = Car(200, "red")
honda = Car(220, "blue")
audi = Car(250, "black")

try:
    print(f"\nSpeed of Ford is --> {ford.s} kmph")
    print(f"Color of Ford is --> {ford.c}")
except Exception as e:
    print(f"\nERROR : {e}")
    quit()